# Generated by Django 4.0.6 on 2024-04-02 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area_cientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('apresentacao', models.CharField(max_length=255)),
                ('objetivo', models.CharField(max_length=255)),
                ('competencia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.IntegerField(default=None)),
                ('semestre', models.IntegerField(default=None)),
                ('ects', models.IntegerField(default=None)),
                ('curricularIUnitReadableCode', models.CharField(max_length=255)),
                ('areaCientifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.area_cientifica')),
            ],
        ),
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=255)),
                ('conceitoAplicado', models.CharField(max_length=255)),
                ('tecnologiaUtilizada', models.CharField(max_length=100)),
                ('linkYotube', models.URLField(blank=True)),
                ('linkGitHub', models.URLField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='')),
                ('disciplina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projeto', to='curso.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('disciplinas', models.ManyToManyField(related_name='docentes', to='curso.disciplina')),
            ],
        ),
    ]
