# Generated by Django 4.0.6 on 2024-04-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='cursos',
            field=models.ManyToManyField(related_name='disciplinas', to='curso.curso'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='semestre',
            field=models.CharField(max_length=100),
        ),
    ]
