# Generated by Django 4.0.6 on 2024-05-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_remove_projeto_disciplina_projeto_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='projeto',
            name='disciplinas',
            field=models.ManyToManyField(related_name='projetos', to='curso.disciplina'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
