# Generated by Django 4.0.6 on 2024-05-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_remove_projeto_disciplina_projeto_disciplinas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
