# Generated by Django 4.0.6 on 2024-03-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='musica',
            name='ano_lancamento',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='musica',
            name='data',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='album',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
