# Generated by Django 4.0.6 on 2024-03-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_banda_foto_musica_ano_lancamento_musica_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
