# Generated by Django 4.0.6 on 2024-03-18 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_alter_musica_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artista',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='ano_lancamento',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='link_spotify',
        ),
        migrations.AddField(
            model_name='album',
            name='ano_lancamento',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='album',
            name='banda',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bandas.banda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='titulo',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banda',
            name='detalhe',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musica',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bandas.album'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musica',
            name='duracao',
            field=models.DurationField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musica',
            name='spotify_link',
            field=models.URLField(blank=True),
        ),
    ]
