# Generated by Django 4.0.6 on 2024-04-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0006_alter_album_capa_alter_banda_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='detalhe',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
