# Generated by Django 4.0.6 on 2024-05-25 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0009_musica_biografia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banda',
            name='detalhe',
        ),
    ]
