# Generated by Django 4.0.6 on 2024-06-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bnadas', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Lei', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Artigos', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Meteo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MeByMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=500)),
                ('interesses', models.CharField(default='Habilidades a serem adicionadas', max_length=1000)),
                ('aptidoes', models.CharField(default='Habilidades a serem adicionadas', max_length=500)),
                ('competencias', models.CharField(default='a serem adicionadas', max_length=500)),
                ('experiencia', models.CharField(default='a serem adicionadas', max_length=5000)),
                ('cv', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='TechPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(max_length=2000)),
                ('technologies', models.TextField(max_length=2000)),
                ('django_hands_on_video', models.URLField()),
                ('project_tour_video', models.URLField()),
            ],
        ),
    ]
