# Generated by Django 4.0.6 on 2024-06-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('interests', models.CharField(default='Habilidades a serem adicionadas', max_length=1000, verbose_name='Interests')),
                ('skills', models.CharField(default='Habilidades a serem adicionadas', max_length=500, verbose_name='Skills')),
                ('competencies', models.CharField(default='a serem adicionadas', max_length=500, verbose_name='Competencies')),
                ('experience', models.CharField(default='a serem adicionadas', max_length=5000, verbose_name='Experience')),
                ('cv_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='CV Image')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandas_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Bandas Image')),
                ('lei_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Lei Image')),
                ('artigos_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Artigos Image')),
                ('meteo_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Meteo Image')),
            ],
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Introduction Text')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField(max_length=2000, verbose_name='Introduction Text')),
                ('tech_details', models.TextField(max_length=2000, verbose_name='Technologies Details')),
                ('django_video_url', models.URLField(verbose_name='Django Hands-on Video URL')),
                ('project_video_url', models.URLField(verbose_name='Project Tour Video URL')),
            ],
        ),
        migrations.DeleteModel(
            name='allApp',
        ),
        migrations.DeleteModel(
            name='Intro',
        ),
        migrations.DeleteModel(
            name='MeByMe',
        ),
        migrations.DeleteModel(
            name='TechPresentation',
        ),
    ]
