# Generated by Django 4.0.6 on 2024-06-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_aboutme_applicationimages_introduction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeByMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=500)),
                ('interesses', models.CharField(default='Habilidades a serem adicionadas', max_length=1000)),
                ('aptidoes', models.CharField(default='Habilidades a serem adicionadas', max_length=500)),
                ('competencias', models.CharField(default='a serem adicionadas', max_length=500)),
                ('experiencia', models.CharField(default='a serem adicionadas', max_length=5000)),
                ('cv', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutMe',
        ),
    ]
