# Generated by Django 4.0.6 on 2024-06-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalpresentation',
            name='django_video_url',
        ),
        migrations.RemoveField(
            model_name='technicalpresentation',
            name='project_video_url',
        ),
        migrations.AlterField(
            model_name='mebyme',
            name='aptidoes',
            field=models.CharField(default='EM BREVE', max_length=500),
        ),
        migrations.AlterField(
            model_name='mebyme',
            name='competencias',
            field=models.CharField(default='EM BREVE', max_length=500),
        ),
        migrations.AlterField(
            model_name='mebyme',
            name='experiencia',
            field=models.CharField(default='EM BREVE', max_length=5000),
        ),
        migrations.AlterField(
            model_name='mebyme',
            name='interesses',
            field=models.CharField(default='EM BREVE', max_length=1000),
        ),
        migrations.AlterField(
            model_name='technicalpresentation',
            name='intro_text',
            field=models.TextField(max_length=2000, verbose_name='TEXTO iNTRODUTORIO'),
        ),
        migrations.AlterField(
            model_name='technicalpresentation',
            name='tech_details',
            field=models.TextField(max_length=2000, verbose_name='DETALHES'),
        ),
    ]
